default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: app_name_placeholder_development

test:
  <<: *default
  database: app_name_placeholder_test

production:
  <<: *default
  database: app_name_placeholder_production
  username: app_name_placeholder
  password: <%= ENV['app_name_placeholder_DATABASE_PASSWORD'] %>
