default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: basic_template_development

test:
  <<: *default
  database: basic_template_test

production:
  <<: *default
  database: basic_template_production
  username: basic_template
  password: <%= ENV['basic_template_DATABASE_PASSWORD'] %>
