name: Linting
on: [push]
jobs:
  ruby:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: etup Ruby
        uses: ruby/setup-ruby@v1
      - name: Install Rubocop
        run: gem install rubocop
      - name: Run Rubocop
        run: |-
          git fetch origin main
          FILES=$(git diff --name-only origin/main -- 'spec/**/*.rb' 'app*/**/*.rb' | grep -v '/old/' || true)
          if [ -z "${FILES}" ]
          then
            echo "No rb changes detected, skipping."
          exit 0
          else
            rubocop ${FILES}
          fi
  javascript:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
    - name: Install Yarn
      run: npm install -g yarn
    - name: Yarn Cache
      id: yarn-cache 
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      run: yarn install
    - name: Run Eslint
      run: |-
        git fetch origin main
        FILES=$(git diff --name-only origin/main -- 'test/**/*.js' 'app*/**/*.js' 'test/**/*.jsx' 'app*/**/*.jsx' | grep -v '/old/' || true)
        if [ -z "${FILES}" ]
        then
          echo "No JS changes detected, skipping."
          exit 0
        else
          yarn run lint ${FILES}
        fi
  

