name: Linting
on: [push]
jobs:
  ruby:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v3.0.0.rc2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  javascript:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
    - name: Install yarn
      run: npm install -g yarn
    - name: Yarn cache
      id: yarn-cache 
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Dependencies
      run: yarn install
    - name: Run Eslint
      run: |-
        git fetch origin main
        FILES=$(git diff --name-only origin/main -- 'test/**/*.js' 'app*/**/*.js' 'test/**/*.jsx' 'app*/**/*.jsx' | grep -v '/old/' || true)
        if [ -z "${FILES}" ]
        then
          echo "No JS changes detected, skipping."
          exit 0
        else
          yarn run lint ${FILES}
        fi
  

